### ISSUE TITLE
When user check dtube channel then there show blank page (no video show here)

### ISSUE THREAD

**Issue by sabbir1213** [dtube/dtube#50] opened 2018-07-11 11:40 UTC
### Expected behavior
When we browse dtube and want to check our channel then dtube should show all video on our channel.

### Actual behavior
If we browse dtube and when want to check our channel all video then dtube can't show any video in this channel. If anyone wants to check their video then their should browse `steemit.com` now, otherwise can't check how many video upload on dtube.

### How to reproduce
- Login dtube with private posting key.
- Browse dtube and go to your channel.
- Check your video section then you will see `blank page` no video here.
- Browser version: Mozilla Firefox 61.0.1 (64-bit)
- Operating system: Windows 7 Professional.

### Recording Of The Bug
https://youtu.be/tQD1y0A4GQc

**Comment by sashaman** [comment] 2019-01-29 16:35
same here, win 10 pro x64, firefox, waterfox as well as chrome all show an empty page 
https://d.tube/#!/c/sempervideo   -> empty page 
FIX: add the closing slash at end of address
https://d.tube/#!/c/sempervideo**/**

dunno why but i hope this gets fixed asap as this is **VERY** annoying
greetings

**Comment by techcoderx** [comment] 2021-07-25 15:54
Probably an old issue that was caused by too many non-DTube posts in the blog. Now that it is mainly using its own chain this should be a non-issue.

**Closed by techcoderx** 2021-07-25 15:54 UTC
