### ISSUE TITLE
cant create a new account on D Tube!!

### ISSUE THREAD

**Issue by BlueBoxReven** [dtube/dtube#134] opened 2020-01-22 07:00 UTC
So I have been combing the internet for an alternative platform to create content and found, DTube, hey! Cool!
So next step, create an account, no problem. Put in my birthday, email, next was the infamous recaptcha thing. Clicked on it, got the green check mark. OK! Clicked send. Immediately got tossed to a webpage stating this: 
{"message":"The security token included in the request is invalid.","code":"InvalidClientTokenId","time":"2020-01-22T06:56:00.420Z","requestId":"96f57682-d230-467a-92d2-e9a741bc254a","statusCode":403,"retryable":false,"retryDelay":45.48520958945772}

Come on guys how am I supposed to get started if I cant even create a log in???

**Comment by DarthVanger** [comment] 2020-02-02 22:00
Same here.
After filling the form and clicking "send email", it either says the security token is invalid:

<img width="918" alt="security-token-dtube" src="https://user-images.githubusercontent.com/6686679/73616117-f792b300-4617-11ea-82e0-bd0a201dd54f.png">

```
{"message":"The security token included in the request is invalid.","code":"InvalidClientTokenId","time":"2020-02-02T21:57:50.141Z","requestId":"13a372db-32fe-400e-a842-99548d8cf218","statusCode":403,"retryable":false,"retryDelay":43.725383613313596}
```

Or it redirects back to the signup page showing "missing data" at the very top of the page:

<img width="1026" alt="dtube-missing-data" src="https://user-images.githubusercontent.com/6686679/73616085-a7b3ec00-4617-11ea-97c5-cbbf52a22223.png">

**Comment by DarthVanger** [comment] 2020-02-02 22:01
And this is a duplicate of https://github.com/dtube/dtube/issues/127

**Comment by skzap** [comment] 2020-03-11 11:52
This broken but got fixed about a month ago. Sorry about the downtime, we had an issue with our email provider.

**Closed by skzap** 2020-03-11 11:52 UTC

**Comment by SomeDevWeb** [comment] 2022-12-12 23:45
I've just tried a few times over the last few days from different browsers and it's down...
Says:
This site can’t be reached
The connection was reset.

**Comment by faustf** [comment] 2024-01-30 16:19
me  tha same proble i think dtube , is fake service
